services:
  portfolio:
    image: portfolio
    build:
      context: .
      dockerfile: Portfolio/Dockerfile
    ports:
        - "8080:8080"
    env_file:
      - .env
  
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"